spring.application.name=dashboard-backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/dashboard_db
spring.datasource.username=dashboard_user
spring.datasource.password=dashboard123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spring Security
spring.security.user.name = nivek
spring.security.user.password = kevin